apiVersion: apps/v1
kind: Deployment
metadata:
  name: honey-trap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honey-trap
  template:
    metadata:
      labels:
        app: honey-trap
    spec:
      containers:
      - name: honey-trap
        image: registry.hub.docker.com/honeytrap/honeytrap:latest
        ports:
        - containerPort: 8022
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        livenessProbe:
          tcpSocket:
            port: 8022
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: honey-trap
spec:
  selector:
    app: honey-trap
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 8022